version: '3.8'
services:
  search:
    image: getmeili/meilisearch
    restart: always
    volumes:
      - meilisearch_data:/data.ms
    environment:
      MEILI_MASTER_KEY: dsfjkljkkfd
    ports:
      - 7700:7700

volumes:
  meilisearch_data:
